version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: jc_app_db
    environment:
      POSTGRES_USER: admin_jc
      POSTGRES_PASSWORD: password_seguro_123
      POSTGRES_DB: jc_recompensas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # LÍNEA MÁGICA: Inyecta el script SQL automáticamente al iniciar por primera vez
      - ./public/db-init:/docker-entrypoint-initdb.d
    networks:
      - jc_network

  backend:
    build: .
    container_name: jc-app-backend
    ports:
      - "3000:3000"
      - "3443:3443"
    environment:
      DATABASE_URL: postgresql://admin_jc:password_seguro_123@db:5432/jc_recompensas
      JWT_SECRET: local_only_change_this_to_a_32_character_secret
      ALLOWED_ORIGIN: https://localhost:3443
      NODE_ENV: development
    depends_on:
      - db
    networks:
      - jc_network

volumes:
  pgdata:

networks:
  jc_network:
